### ISSUE TITLE
Težava

### ISSUE THREAD

**Issue by vitorozman** [MatejRojec/Uravnotezen-rdece-modri-povezan-podgraf#1]
Pozdrav @jaanos , 
imamo še eno težavo.
Sedaj smo odpravili težavo pri delu ko je `fj == 0` in smo se lotili problema na grafih P_3 in P_4, kjer ne vemo kako pravilno ločiti vorce, da izberemo enkrat povezanega drugič nepovezanega, glede na to ali v prihodnje najdemo vzorec ki poveže komponente. Poskusili smo vstaviti še eno spremenljivko `V` kamor vnašamo vzorce do koraka ijv, vendar ne vemo kako pri iskanju p* najdemo takega, ki je iz enen komponente.
V mapi **ALGO_BCS** imao **modelBCS.py** , kjer so potrebne funkcije za glavni algoritem ter v skripti **algoritem.py**  je glavna funkcija `P(G)`, ki poišče vse _p_ijv_ in `max_BCS(G)`, ki vrne največji uteženi podgraf in vozlišča.

**Comment by jaanos** [comment]
Svetujem, da vzorce predstavite kot particijo množice povezanih komponent podgrafa. V primeru poti na treh vozliščih imate torej take vzorce:
```
v1 = [[[1]]]
v2 = [[[2]]]
v3 = [[[3]]]
v4 = [[[1, 2]]]
v5 = [[[1], [3]]]
v6 = [[[1]], [[3]]]
v7 = [[[2, 3]]]
v8 = [[[1, 2, 3]]]
```
Tukaj vsaka množica v vzorcu (recimo ji _del_) pove, za katere _komponente_ (tj., povezane komponente podgrafa - elementi dela) je zagotovljena medsebojna povezanost. Vzorec je tako _povezan_, če ima en sam del (samo te vzorce obravnavamo pri končni rešitvi - vmesne rezultate seveda računamo za vse vzorce). Vzorec _u_ je lahko predhodnik vzorca _v_, če velja sledeče: 
1. v vsakem delu vzorca _u_ obstaja vozlišče, ki je vsebovano v vzorcu _v_ (tj., noben del _u_ ne ostane odrezan), in
2. za vsak del vzorca _v_ velja, da obstaja pot (preko _u_ in pri njem zagotovljenih povezav) med vsakima njegovima komponentama (tj., zagotovimo želeno medsebojno povezanost).

Prvi pogoj bo enostavno preveriti, npr.
```python
du = [set(sum(d, [])) for d in u] # deli u
vv = set(sum(sum(v, []),[])) # množica vozlišč v
pogoj1 = all(any(x in vv for x in d) for d in du)
```
Za drugi pogoj bi bilo v splošnem treba določiti povezane komponente grafa, ki ga dobite iz vzorcev _u_ in _v_, kar bi lahko dobili z iskanjem v širino. Če se omejite na poti z največ 4 vozlišči, pa bo zadostovalo, če preverite, da za vsak del _d_ vzorca _v_ z več kot eno komponento obstaja tak del _u_, ki vsebuje vozlišče iz vsake komponente _d_ (tj., kot da bi naredili iskanje v širino do globine 2):
```python
pogoj2 = all(any(all(any(x in c for x in e) for c in d) for e in du) for d in v if len(d) > 1)
```
Mislim, da bi to moralo zadostovati tudi za poti na 5 in 6 vozliščih. Za poti na 7 ali več vozliščih pa ne bi šlo, saj bi tako spregledali primer `u = [[[1, 2, 3]], [[5, 6, 7]]]`, `v = [[[1], [3, 4, 5], [7]]]`.

V zgornjem primeru so povezani vsi vzorci, razen `v6` (vzorec `v5` je povezan, saj predpostavlja, da sta komponenti povezani preko predhodnih vzorcev). Vzorcu `v4` npr. lahko sledi vzorec `v6`, saj ta ne predpostavlja, da sta komponenti med seboj povezani (za to bodo morali poskrbeti prihodnji vzorci) - ne sme mu pa slediti vzorec `v5`.

Potrebno bo paziti še, da prvi vzorec nima nobenega dela z več kot eno komponento (zgoraj je tak edino `v5`) - ko računate vrednost za tak vzorec, bo treba izmed kandidatov za predhodnika torej izločiti tiste, kjer je vrednost enaka 0.

Vidim še, da ste pripravili razred, ki v konstruktorju sprejme kar celoten graf oziroma njegovo barvanje. Namesto tega svetujem, da v konstruktorju podaste samo osnovni graf (če se omejite na poti, je to lahko samo število njegovih vozlišč - tj., število "vrstic") in se na podlagi tega izračunajo vzorci in njihova združljivost (morda lahko vnaprej ugotovite, kateri so dovoljeni začetni vzorci ter kateri so povezani). Tako dobljeni objekt lahko potem uporabite za iskanje ustrezne uravnotežene množice za različne grafe (tj., različna števila "stolpcev" in različna barvanja).

**Comment by vitorozman** [comment]
Pozdrav @jaanos .
Sedaj smo vključili še _pogoj1_ in _pogoj2_, vendar smo naleteli na problem, da nam včasih algoritem `max_BCS(G)` vrne liho število, npr pri primer G = [[1], [1], [1], [1], [1], [-1], [-1], [1], [1], [-1], [1], [1]] (ko mamo pot). Ponavadi se to število razlikuje za ena, torej namesto 6 dobimo 5 in podobno.

Dodali smo tudi spremenljivko, ki si zapomni vozlišča za največji uteženi podgraf.

Ko pogledamo koliko je vozlišč pa dobimo 8:
```
G6 = [[1], [1], [1], [1], [1], [-1], [-1], [1], [1], [-1], [-1], [1]] 
print(max_BCS(G6))
(7, [[[[[[[[None, [[[1]]]], [[[1]]]], [[[1]]]], [[[1]]]], [[[1]]]], [[[1]]]], [[[1]]]], [[[1]]]])
```
Prav tako nas zamina kako bi lahko lepše izpisali končen graf z vozlišči, saj nismo našli dobre rešitve.

**Comment by jaanos** [comment]
Kolikor vidim, je težava tukaj:
https://github.com/MatejRojec/Uravnotezen-rdece-modri-povezan-podgraf/blob/f8394dfd7f678d26757df3508003aa3c77dc6a02/ALGO_BCS/algoritem.py#L36-L39
V drugem primeru bo treba vzeti vrednost 0 - tj., do trenutnega stolpca ne vzamemo nobenega vozlišča. Potrebno bo popraviti tudi sledeče:
https://github.com/MatejRojec/Uravnotezen-rdece-modri-povezan-podgraf/blob/f8394dfd7f678d26757df3508003aa3c77dc6a02/ALGO_BCS/algoritem.py#L50
Tukaj gre za to, da vzorca ni mogoče uporabiti, če predpostavlja povezanost med komponentama, a pred tem ni bilo uporabljeno še nobeno vozlišče. To bi lahko zapisali tako:
```python
if any(len(d) > 1 for d in vzorec[v]) and p[i - 1][j - vr_vz][u] == 0:
```
Ta pogoj na vzorcu bo potrebno preveriti tudi v prvem stolpcu (tj., ko je `i == 0`), saj takrat predhodnih vozlišč zagotovo ni.

Sicer pa, kot rečeno, svetujem, da si vnaprej pripravite seznam možnih začetnih vzorcev (tj., takih, ki ne ustrezajo zgornjemu pogoju) in za vsak vzorec seznam njegovih možnih predhodnikov, tako da vam tega ni potrebno početi vsakič sproti.

**Comment by MatejRojec** [comment]
Najlepša hvala,
sedaj algoritem dela tako kot more.
